# Generated by Django 5.2.4 on 2025-10-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloth',
            name='image',
        ),
        migrations.AddField(
            model_name='cloth',
            name='image_front',
            field=models.ImageField(blank=True, null=True, upload_to='clothes/front/'),
        ),
        migrations.AddField(
            model_name='cloth',
            name='image_left',
            field=models.ImageField(blank=True, null=True, upload_to='clothes/left/'),
        ),
        migrations.AddField(
            model_name='cloth',
            name='image_right',
            field=models.ImageField(blank=True, null=True, upload_to='clothes/right/'),
        ),
        migrations.AddField(
            model_name='cloth',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
