# Generated by Django 5.2.4 on 2025-11-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_category_options_category_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], help_text='Rating from 1 to 5 stars')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="User's IP address for tracking", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Site Rating',
                'verbose_name_plural': 'Site Ratings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Customer's name", max_length=100)),
                ('contact', models.CharField(blank=True, help_text='Email or phone number (optional)', max_length=100)),
                ('review_text', models.TextField(help_text="Customer's written review")),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_approved', models.BooleanField(default=True, help_text='Approve review for display')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Site Review',
                'verbose_name_plural': 'Site Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
